In [1]:
import numpy as np

In [3]:
arr =  np.array([23 ,34, 45,67,78])

In [4]:
print(arr)

[23 34 45 67 78]


In [5]:
type(arr)

numpy.ndarray

In [6]:
arr[2]

45

In [10]:
arr[2]=100

In [11]:
print(arr)

[ 23  34 100  67  78]


In [13]:
arr1 = np.array([23 , 56.78 ,'pune',True])

In [14]:
arr1

array(['23', '56.78', 'pune', 'True'], dtype='<U32')

In [16]:
arr1.dtype

dtype('<U32')

#### Check which is faster list or array

In [18]:
import time

In [19]:
time.time()

1750657513.8711634

In [20]:
s = 100000

list1 = list(range(s))

arr1 = np.array(list)

In [21]:
arr1

array(<class 'list'>, dtype=object)

In [24]:
# for list
start_time=time.time()
x =  [i * 2 for i in list1]
time_list = time.time()-start_time
print('time taken by list:' , time_list)

time taken by list: 0.007646083831787109


In [ ]:
arr1 =

In [28]:
# for array
start_time=time.time()
y =  arr1 * 2
time_arr = time.time()-start_time
print('time taken by list:' , time_arr)

time taken by list: 0.0005984306335449219


In [27]:
arr1 = np.array([10 ,20 ,30, 40 , 50])

In [29]:
time_list/time_arr

12.776892430278885

In [33]:
import numpy as np
a = np.arange(11)

In [34]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
arr

array([ 23,  34, 100,  67,  78])

In [38]:
arr.ndim

1

# 2 - d array

In [40]:
arr = np.array([[1 , 2 , 3],[4 , 5 , 6],[7 , 8 ,9]])

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.ndim

2

In [44]:
arr.size

9

In [45]:
arr.shape

(3, 3)

In [46]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr.flatten().ndim

1

In [48]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr = np.array([[1 , 2 , 3],[4 , 5 , 6],[7 , 8 ,9],[10 , 11 , 12]])

In [54]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [55]:
arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

##### Slicing

In [58]:
arr1 = np.array([1 , 2 ,3 , 4 , 5 , 6])

In [59]:
arr1[3:5]

array([4, 5])

In [60]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
arr[1:3 , 0:2]

array([[4, 5],
       [7, 8]])

In [64]:
arr[1:3 , 0:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [65]:
np.mean(arr1)

3.5

In [66]:
np.std(arr1)

1.707825127659933

#### Linear alg

In [69]:
a = np.array([[1 , 2], [3 ,4]])

In [70]:
b = np.array([[5 , 6], [7 ,8]])

In [71]:
a

array([[1, 2],
       [3, 4]])

In [72]:
b

array([[5, 6],
       [7, 8]])

In [74]:
np.dot(a , b)

array([[19, 22],
       [43, 50]])

In [75]:
a @ b

array([[19, 22],
       [43, 50]])

In [76]:
np.linalg.det(a)

-2.0000000000000004

In [77]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [79]:
# vector
vec = np.array([3,6])

In [80]:
np.linalg.norm(vec)

6.708203932499369

In [82]:
# 1
arr = np.array([[1, 2 , 3],[4 , 5 , 6],[7 , 8 , 9]])

In [83]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
arr1 = np.array([10 , 20 , 30 , 40 , 50])

In [85]:
arr1

array([10, 20, 30, 40, 50])

In [87]:
arr1[::-1]

array([50, 40, 30, 20, 10])

In [92]:
arr2 = np.array([[0,0,0,0,0],[0,0,0,0,0],[0,0,1,0,0],[0,0,0,0,0],[0,0,0,0,0]])

In [93]:
arr2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [103]:
arr3 = np.array([12 , 34, 56, 67, 87, 13 , 54, 32 , 87, 98, 9, 56 ,31, 41 , 61, 37, 84, 19, 10, 20])

In [104]:
arr3

array([12, 34, 56, 67, 87, 13, 54, 32, 87, 98,  9, 56, 31, 41, 61, 37, 84,
       19, 10, 20])

In [105]:
arr3[arr3 %2 == 0]=-1

In [106]:
arr3

array([-1, -1, -1, 67, 87, 13, -1, -1, 87, -1,  9, -1, 31, 41, 61, 37, -1,
       19, -1, -1])

In [108]:
a = np.array([[1 , 2], [ 3 , 4], [ 5, 6]])

In [109]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [120]:
a[1:2 , :]

array([[3, 4]])

In [121]:
a = np.array([1 , 2 , 3 , 4])

In [122]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])